baseURL = 'https://netr.dev/'
languageCode = 'en-us'
title = "netr."

# URL
[permalinks]
    [permalinks.page]
        blog = '/blog/:year/:month/:day/:slug/'

# Theme
theme = "hugo-theme-m10c"

# Menu
[menus]
  [[menus.main]]
    name = 'blog'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'portfolio'
    pageRef = '/portfolio'
    weight = 20
  [[menus.main]]
    name = 'books'
    pageRef = '/books'
    weight = 30

[params]
    author = "Corey Jackson"
    description = "software, system design, distributed systems, ai, maths, reading and whatever else proves interesting."
    avatar = "images/avatar.webp"
    menu_item_separator = "•"
    favicon = "/favicon.ico"

[[params.social]]
    icon = "brand-github"
    name = "My Github"
    url = "https://github.com/netr"

[[params.social]]
    icon = "brand-x"
    name = "My X"
    url = "https://twitter.com/netrdev"

[[params.social]]
    icon = "at-sign"
    name = "My Email"
    url = "mailto:corey@netr.dev"

[params.style]
    darkestColor = "#181926"
    darkColor = "#24273a" 
    lightColor = "#CAD3F5"
    lightestColor = "#f5f5f5"
    primaryColor = "#c6a0f6"
    secondaryColor = "#8BD5CA"

[markup]
    [markup.highlight]
        lineNoStart = 1
        lineNos = true
        noClasses = false
        codeFences = true